version: '3.7'

services:
  mongo:
    image: postgres
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - 27017:27017

  client:
    build: client
    restart: always
    container_name: client
    depends_on:
      - server

  server:
    build: server
    ports:
    - 4004:4004
    restart: always
    container_name: server
    depends_on:
      - mongo