version: '3.7'

services:
  mongo:
    image: mongo
    container_name: database
    restart: always
    environment:
      MONGODB_USER: admin
      MONGODB_DATABASE: mongo
      MONGODB_PASS: pass
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  client:
    build: client
    restart: always
    container_name: client
    depends_on:
      - server

  server:
    build: server
    ports:
    - 4004:4004
    restart: always
    container_name: server
    depends_on:
      - mongo

volumes:
  mongodb_data:
    driver: local