version: '3.7'

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432

  client:
    build: client
    restart: always
    container_name: client
    depends_on:
      - server

  server:
    build: server
    ports:
    - 4004:4004
    restart: always
    container_name: server
    depends_on:
      - postgres